export default {
    ACTIONS: {
        LOGIN_SUCCESS: 'LOGIN_SUCCESS',
        LOGIN_ERROR: 'LOGIN_ERROR',
        CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
        CREATE_ACCOUNT_ERROR: 'CREATE_ACCOUNT_ERROR',
        FETCH_ACCOUNT_SUCCESS: 'FETCH_ACCOUNT_SUCCESS',
        FETCH_ACCOUNT_ERROR: 'FETCH_ACCOUNT_ERROR',
        UPDATE_ACCOUNT_SUCCESS: 'UPDATE_ACCOUNT_SUCCESS',
        UPDATE_ACCOUNT_ERROR: 'UPDATE_ACCOUNT_ERROR'
    }
}